use: |-
  configure [argument] [flags]

  Arguments:
    {{ arguments }}
example: |-
  To create a new named profile:
    tecli configure --profile work

  To delete a named profile:
    tecli configure delete --profile work

  To crate a new named profile non-interactivelly:
    tecli configure create --profile cicd --mode=non-interactive

short: Configures tecli settings
long: |
  Configure TECLI options. If this command is run with create argument, you will be prompted for configuration values such as your Terraform Cloud Team Token. 
  You can configure a named profile using the --profile argument. If your config file does not exist, the TECLI will create it for you. 
  To keep an existing value, hit enter when prompted for the value. When you are prompted for information, the current value will be displayed in [brackets]. 
  If the config item has no value, it won't be displayed. Note that the configure command only works with values from the config file. It does not use any configuration values from environment variables.